#!/usr/bin/env python
import boto3
import xlwt
from xlwt import Workbook
# Workbook is created
#wb = Workbook()
# add_sheet is used to create sheet.
#sheet1 = wb.add_sheet('Sheet 1')
#sheet1.write(0, 0, 'ETAG')
client = boto3.client('s3')
response = client.list_objects(
        Bucket='fmc-prod-repo-usw2'
        )
#j=1
#for i in response['Contents']:
#        print(i['ETag'])
#        sheet1.write(j,0,i['ETag'])
#        j = j+1
#wb.save("Etag_example.xls")


#for i in range(0,2):
#    print(response['Contents'][i]['ETag'])
#    sheet1.write(i+1,0,response['Contents'][i]['ETag'])
#wb.save("Etag2_example.xls")
print(response)
~               
